apiVersion: apps/v1
kind: Deployment
metadata:
  name: whizapp-deployment
spec:
  selector:
    matchLabels:
      app: whizapp
  replicas: 2
  template:
    metadata:
      labels:
        app: whizapp
    spec:
      containers:
        - name: whizapp
          image: whizdome/whizapp:3
          ports:
            - containerPort: 8080
