name: CI

on:
  push:
    branches:
      - main  # Adjust branch name as per your setup
  pull_request:
    branches:
      - main  # Adjust branch name as per your setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Adjust to a supported Node.js version

      - name: Update npm
        run: npm install -g npm@latest

      - name: Update dependencies
        run: npm update

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Test
        run: npm test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
